<?php

/*
 * File: ratatoeskr/languages.php
 */

/*
 * Array: $languages
 * Information about a lot of languages.
 *
 * $languages is a global array. The array keys represent the ISO 639-1 code of the language.
 * The values are arrays with these keys:
 *
 * "language"          - The Name of the language in this language (UTF-8 encoded)
 * "translation_exist" - True, if there is a translation file for this language.
 *
 * Source:
 *  http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
 */
$languages = [
    "aa" => ["language" => "Afaraf", "translation_exist" => false],
    "ab" => ["language" => "аҧсуа", "translation_exist" => false],
    "ae" => ["language" => "avesta", "translation_exist" => false],
    "af" => ["language" => "Afrikaans", "translation_exist" => false],
    "ak" => ["language" => "Akan", "translation_exist" => false],
    "am" => ["language" => "አማርኛ", "translation_exist" => false],
    "an" => ["language" => "Aragonés", "translation_exist" => false],
    "ar" => ["language" => "العربية", "translation_exist" => false],
    "as" => ["language" => "অসমীয়া", "translation_exist" => false],
    "av" => ["language" => "авар мацӀ, магӀарул мацӀ", "translation_exist" => false],
    "ay" => ["language" => "aymar aru", "translation_exist" => false],
    "az" => ["language" => "azərbaycan dili", "translation_exist" => false],
    "ba" => ["language" => "башҡорт теле", "translation_exist" => false],
    "be" => ["language" => "Беларуская", "translation_exist" => false],
    "bg" => ["language" => "български език", "translation_exist" => false],
    "bh" => ["language" => "भोजपुरी", "translation_exist" => false],
    "bi" => ["language" => "Bislama", "translation_exist" => false],
    "bm" => ["language" => "bamanankan", "translation_exist" => false],
    "bn" => ["language" => "বাংলা", "translation_exist" => false],
    "bo" => ["language" => "བོད་ཡིག", "translation_exist" => false],
    "br" => ["language" => "brezhoneg", "translation_exist" => false],
    "bs" => ["language" => "bosanski jezik", "translation_exist" => false],
    "ca" => ["language" => "Català", "translation_exist" => false],
    "ce" => ["language" => "нохчийн мотт", "translation_exist" => false],
    "ch" => ["language" => "Chamoru", "translation_exist" => false],
    "co" => ["language" => "corsu, lingua corsa", "translation_exist" => false],
    "cr" => ["language" => "ᓀᐦᐃᔭᐍᐏᐣ", "translation_exist" => false],
    "cs" => ["language" => "česky, čeština", "translation_exist" => false],
    "cu" => ["language" => "ѩзыкъ словѣньскъ", "translation_exist" => false],
    "cv" => ["language" => "чӑваш чӗлхи", "translation_exist" => false],
    "cy" => ["language" => "Cymraeg", "translation_exist" => false],
    "da" => ["language" => "dansk", "translation_exist" => false],
    "de" => ["language" => "Deutsch", "translation_exist" => true],
    "dv" => ["language" => "ދިވެހި", "translation_exist" => false],
    "dz" => ["language" => "རྫོང་ཁ", "translation_exist" => false],
    "ee" => ["language" => "Eʋegbe", "translation_exist" => false],
    "el" => ["language" => "Ελληνικά", "translation_exist" => false],
    "en" => ["language" => "English", "translation_exist" => true],
    "eo" => ["language" => "Esperanto", "translation_exist" => false],
    "es" => ["language" => "español, castellano", "translation_exist" => false],
    "et" => ["language" => "eesti, eesti keel", "translation_exist" => false],
    "eu" => ["language" => "euskara, euskera", "translation_exist" => false],
    "fa" => ["language" => "فارسی", "translation_exist" => false],
    "ff" => ["language" => "Fulfulde, Pulaar, Pular", "translation_exist" => false],
    "fi" => ["language" => "suomi, suomen kieli", "translation_exist" => false],
    "fj" => ["language" => "vosa Vakaviti", "translation_exist" => false],
    "fo" => ["language" => "føroyskt", "translation_exist" => false],
    "fr" => ["language" => "français, langue française", "translation_exist" => false],
    "fy" => ["language" => "Frysk", "translation_exist" => false],
    "ga" => ["language" => "Gaeilge", "translation_exist" => false],
    "gd" => ["language" => "Gàidhlig", "translation_exist" => false],
    "gl" => ["language" => "Galego", "translation_exist" => false],
    "gn" => ["language" => "Avañe'ẽ", "translation_exist" => false],
    "gu" => ["language" => "ગુજરાતી", "translation_exist" => false],
    "gv" => ["language" => "Gaelg, Gailck", "translation_exist" => false],
    "ha" => ["language" => "Hausa, هَوُسَ", "translation_exist" => false],
    "he" => ["language" => "עברית", "translation_exist" => false],
    "hi" => ["language" => "हिन्दी, हिंदी", "translation_exist" => false],
    "ho" => ["language" => "Hiri Motu", "translation_exist" => false],
    "hr" => ["language" => "hrvatski", "translation_exist" => false],
    "ht" => ["language" => "Kreyòl ayisyen", "translation_exist" => false],
    "hu" => ["language" => "Magyar", "translation_exist" => false],
    "hy" => ["language" => "Հայերեն", "translation_exist" => false],
    "hz" => ["language" => "Otjiherero", "translation_exist" => false],
    "ia" => ["language" => "Interlingua", "translation_exist" => false],
    "id" => ["language" => "Bahasa Indonesia", "translation_exist" => false],
    "ie" => ["language" => "Originally called ", "translation_exist" => false],
    "ig" => ["language" => "Asụsụ Igbo", "translation_exist" => false],
    "ii" => ["language" => "ꆈꌠ꒿ Nuosuhxop", "translation_exist" => false],
    "ik" => ["language" => "Iñupiaq, Iñupiatun", "translation_exist" => false],
    "io" => ["language" => "Ido", "translation_exist" => false],
    "is" => ["language" => "Íslenska", "translation_exist" => false],
    "it" => ["language" => "Italiano", "translation_exist" => false],
    "iu" => ["language" => "ᐃᓄᒃᑎᑐᑦ", "translation_exist" => false],
    "ja" => ["language" => "日本語 (にほんご)", "translation_exist" => false],
    "jv" => ["language" => "basa Jawa", "translation_exist" => false],
    "ka" => ["language" => "ქართული", "translation_exist" => false],
    "kg" => ["language" => "KiKongo", "translation_exist" => false],
    "ki" => ["language" => "Gĩkũyũ", "translation_exist" => false],
    "kj" => ["language" => "Kuanyama", "translation_exist" => false],
    "kk" => ["language" => "Қазақ тілі", "translation_exist" => false],
    "kl" => ["language" => "kalaallisut, kalaallit oqaasii", "translation_exist" => false],
    "km" => ["language" => "ភាសាខ្មែរ", "translation_exist" => false],
    "kn" => ["language" => "ಕನ್ನಡ", "translation_exist" => false],
    "ko" => ["language" => "한국어 (韓國語), 조선어 (朝鮮語)", "translation_exist" => false],
    "kr" => ["language" => "Kanuri", "translation_exist" => false],
    "ks" => ["language" => "कश्मीरी, كشميري‎", "translation_exist" => false],
    "ku" => ["language" => "Kurdî, كوردی‎", "translation_exist" => false],
    "kv" => ["language" => "коми кыв", "translation_exist" => false],
    "kw" => ["language" => "Kernewek", "translation_exist" => false],
    "ky" => ["language" => "кыргыз тили", "translation_exist" => false],
    "la" => ["language" => "latine, lingua latina", "translation_exist" => false],
    "lb" => ["language" => "Lëtzebuergesch", "translation_exist" => false],
    "lg" => ["language" => "Luganda", "translation_exist" => false],
    "li" => ["language" => "Limburgs", "translation_exist" => false],
    "ln" => ["language" => "Lingála", "translation_exist" => false],
    "lo" => ["language" => "ພາສາລາວ", "translation_exist" => false],
    "lt" => ["language" => "lietuvių kalba", "translation_exist" => false],
    "lu" => ["language" => "Luba-Katanga", "translation_exist" => false],
    "lv" => ["language" => "latviešu valoda", "translation_exist" => false],
    "mg" => ["language" => "Malagasy fiteny", "translation_exist" => false],
    "mh" => ["language" => "Kajin M̧ajeļ", "translation_exist" => false],
    "mi" => ["language" => "te reo Māori", "translation_exist" => false],
    "mk" => ["language" => "македонски јазик", "translation_exist" => false],
    "ml" => ["language" => "മലയാളം", "translation_exist" => false],
    "mn" => ["language" => "монгол", "translation_exist" => false],
    "mr" => ["language" => "मराठी", "translation_exist" => false],
    "ms" => ["language" => "bahasa Melayu, بهاس ملايو‎", "translation_exist" => false],
    "mt" => ["language" => "Malti", "translation_exist" => false],
    "my" => ["language" => "ဗမာစာ", "translation_exist" => false],
    "na" => ["language" => "Ekakairũ Naoero", "translation_exist" => false],
    "nb" => ["language" => "Norsk bokmål", "translation_exist" => false],
    "nd" => ["language" => "isiNdebele", "translation_exist" => false],
    "ne" => ["language" => "नेपाली", "translation_exist" => false],
    "ng" => ["language" => "Owambo", "translation_exist" => false],
    "nl" => ["language" => "Nederlands, Vlaams", "translation_exist" => false],
    "nn" => ["language" => "Norsk nynorsk", "translation_exist" => false],
    "no" => ["language" => "Norsk", "translation_exist" => false],
    "nr" => ["language" => "isiNdebele", "translation_exist" => false],
    "nv" => ["language" => "Diné bizaad, Dinékʼehǰí", "translation_exist" => false],
    "ny" => ["language" => "chiCheŵa, chinyanja", "translation_exist" => false],
    "oc" => ["language" => "Occitan", "translation_exist" => false],
    "oj" => ["language" => "ᐊᓂᔑᓈᐯᒧᐎᓐ", "translation_exist" => false],
    "om" => ["language" => "Afaan Oromoo", "translation_exist" => false],
    "or" => ["language" => "ଓଡ଼ିଆ", "translation_exist" => false],
    "os" => ["language" => "ирон æвзаг", "translation_exist" => false],
    "pa" => ["language" => "ਪੰਜਾਬੀ, پنجابی‎", "translation_exist" => false],
    "pi" => ["language" => "पाऴि", "translation_exist" => false],
    "pl" => ["language" => "polski", "translation_exist" => false],
    "ps" => ["language" => "پښتو", "translation_exist" => false],
    "pt" => ["language" => "Português", "translation_exist" => false],
    "qu" => ["language" => "Runa Simi, Kichwa", "translation_exist" => false],
    "rm" => ["language" => "rumantsch grischun", "translation_exist" => false],
    "rn" => ["language" => "Ikirundi", "translation_exist" => false],
    "ro" => ["language" => "română", "translation_exist" => false],
    "ru" => ["language" => "русский язык", "translation_exist" => false],
    "rw" => ["language" => "Ikinyarwanda", "translation_exist" => false],
    "sa" => ["language" => "संस्कृतम्", "translation_exist" => false],
    "sc" => ["language" => "sardu", "translation_exist" => false],
    "sd" => ["language" => "yângâ tî sängö", "translation_exist" => false],
    "se" => ["language" => "Davvisámegiella", "translation_exist" => false],
    "sg" => ["language" => "yângâ tî sängö", "translation_exist" => false],
    "si" => ["language" => "සිංහල", "translation_exist" => false],
    "sk" => ["language" => "slovenčina", "translation_exist" => false],
    "sl" => ["language" => "slovenščina", "translation_exist" => false],
    "sm" => ["language" => "gagana fa'a Samoa", "translation_exist" => false],
    "sn" => ["language" => "chiShona", "translation_exist" => false],
    "so" => ["language" => "Soomaaliga, af Soomaali", "translation_exist" => false],
    "sq" => ["language" => "Shqip", "translation_exist" => false],
    "sr" => ["language" => "српски језик", "translation_exist" => false],
    "ss" => ["language" => "SiSwati", "translation_exist" => false],
    "st" => ["language" => "Sesotho", "translation_exist" => false],
    "su" => ["language" => "Basa Sunda", "translation_exist" => false],
    "sv" => ["language" => "svenska", "translation_exist" => false],
    "sw" => ["language" => "Kiswahili", "translation_exist" => false],
    "ta" => ["language" => "தமிழ்", "translation_exist" => false],
    "te" => ["language" => "తెలుగు", "translation_exist" => false],
    "tg" => ["language" => "   тоҷикӣ, toğikī, تاجیکی‎", "translation_exist" => false],
    "th" => ["language" => "ไทย", "translation_exist" => false],
    "ti" => ["language" => "ትግርኛ", "translation_exist" => false],
    "tk" => ["language" => "Türkmen, Түркмен", "translation_exist" => false],
    "tl" => ["language" => "Wikang Tagalog", "translation_exist" => false],
    "tn" => ["language" => "Setswana", "translation_exist" => false],
    "to" => ["language" => "faka Tonga", "translation_exist" => false],
    "tr" => ["language" => "Türkçe", "translation_exist" => false],
    "ts" => ["language" => "Xitsonga", "translation_exist" => false],
    "tt" => ["language" => "татарча, tatarça, تاتارچا‎", "translation_exist" => false],
    "tw" => ["language" => "Twi", "translation_exist" => false],
    "ty" => ["language" => "Reo Tahiti", "translation_exist" => false],
    "ug" => ["language" => "Uyƣurqə, ئۇيغۇرچە‎", "translation_exist" => false],
    "uk" => ["language" => "українська", "translation_exist" => false],
    "ur" => ["language" => "اردو", "translation_exist" => false],
    "uz" => ["language" => "O'zbek, Ўзбек, أۇزبېك‎", "translation_exist" => false],
    "ve" => ["language" => "Tshivenḓa", "translation_exist" => false],
    "vi" => ["language" => "Tiếng Việt", "translation_exist" => false],
    "vo" => ["language" => "Volapük", "translation_exist" => false],
    "wa" => ["language" => "Walon", "translation_exist" => false],
    "wo" => ["language" => "Wollof", "translation_exist" => false],
    "xh" => ["language" => "isiXhosa", "translation_exist" => false],
    "yi" => ["language" => "ייִדיש", "translation_exist" => false],
    "yo" => ["language" => "Yorùbá", "translation_exist" => false],
    "za" => ["language" => "Saɯ cueŋƅ, Saw cuengh", "translation_exist" => false],
    "zh" => ["language" => "中文, 汉语, 漢語", "translation_exist" => false],
    "zu" => ["language" => "isiZulu", "translation_exist" => false]
];
